### ISSUE TITLE
How can we set the side dependant on media query?

### ISSUE THREAD

**Issue by jezmck** [720kb/angular-tooltips#180]
I have the following (S)CSS which works fine, but the `smart: true` setting puts the tooltip to the top instead of the left.

```css
@media (max-width: 767px) {
  tooltip {
    display: inline-block;
    float: right
  }
}
```

How can I persuade the tooltip to be on the left for small screens and `smart`ly positioned otherwise?
